### ISSUE TITLE
Build error with MacOSX10.14.sdk (deprecated API)

### ISSUE THREAD

**Issue by snuarc** [tholu/homebrew-tap#6] opened 2018-11-11 16:32 UTC
Hi,

I have tried to build subversion18 with unicode_path, but in vain. Could you help? Here I attach my console snapshot:

```
$ brew config
HOMEBREW_VERSION: 1.8.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f458aaed494eaab92622f41f9f1967add00b0f4
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: def087b51b53d8a205bd33d03e05ce8a9a65f91b
Core tap last commit: 62 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.8.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11


$ brew cleanup
Removing: /Users/jaewlee/Library/Caches/Homebrew/subversion18--patch--2eaee628e3161bce4b1697660281cab30f42265369bfa7074ea435e441d543e7.patch... (4.4KB)
==> This operation has freed approximately 4.4KB of disk space.


$ brew remove subversion18
Error: No such keg: /usr/local/Cellar/subversion18


$ brew install subversion18 --with-unicode-path
==> Installing subversion18 from tholu/tap
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.8.16.tar.bz2
Already downloaded: /Users/jaewlee/Library/Caches/Homebrew/downloads/739776cd56d0ee92a7e0915f4ea1bade82c80b68ef6526f210aac0684bac7786--subversion-1.8.16.tar.bz2
==> Downloading https://gist.githubusercontent.com/tholu/fb5d30c586e33b53ecba/raw/a266b1aa01f95cdc38fcedda4c6bce253dfb58c2/svn_1.8.x
######################################################################## 100.0%
==> Patching
patching file configure
Hunk #1 succeeded at 25433 (offset 67 lines).
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Applying svn_1.8.x_darwin_unicode_precomp.patch
patching file subversion/libsvn_subr/io.c
patching file subversion/libsvn_subr/path.c
patching file subversion/svn/proplist-cmd.c
patching file subversion/svn/status-cmd.c
==> Downloading https://archive.apache.org/dist/serf/serf-1.3.8.tar.bz2
Already downloaded: /Users/jaewlee/Library/Caches/Homebrew/downloads/21bc402f7e59867bb8a6027535b1c5cda70bae29838d2398fff3d60ff35fdf97--serf-1.3.8.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion18/1.8.16/libexec/serf GSSAPI=/usr CC=/usr/bin/clang CFLAGS=-O
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion18/1.8.16 --with-zlib=/usr --with-sqlite=/usr/local/opt/sqlite --with-serf=/usr
==> make
Last 15 lines from /Users/jaewlee/Library/Logs/Homebrew/subversion18/04.make:
                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:355:46: error: expected a version of the form 'major[.minor[.subminor]]'
                                    ios(2.0, API_TO_BE_DEPRECATED),
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:356:50: error: expected a version of the form 'major[.minor[.subminor]]'
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
                                              ^
/bin/sh /private/tmp/subversion18-20181112-97552-1l4scpa/subversion-1.8.16/libtool --tag=CC --silent --mode=compile /usr/bin/clang -std=c90  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10   -Werror=unknown-warning-option -Os -w -pipe -march=native -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -O2  -DNDEBUG  -I./subversion/include -I./subversion -I/usr/local/opt/apr/libexec/include/apr-1   -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/subversion18/1.8.16/libexec/serf/include/serf-1 -I/usr/local/opt/sqlite/include -I/usr/include  -o subversion/libsvn_subr/opt.lo -c subversion/libsvn_subr/opt.c
/bin/sh /private/tmp/subversion18-20181112-97552-1l4scpa/subversion-1.8.16/libtool --tag=CC --silent --mode=compile /usr/bin/clang -std=c90  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10   -Werror=unknown-warning-option -Os -w -pipe -march=native -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -O2  -DNDEBUG  -I./subversion/include -I./subversion -I/usr/local/opt/apr/libexec/include/apr-1   -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/subversion18/1.8.16/libexec/serf/include/serf-1 -I/usr/local/opt/sqlite/include -I/usr/include  -o subversion/libsvn_subr/path.lo -c subversion/libsvn_subr/path.c
4 errors generated.
make: *** [subversion/libsvn_subr/macos_keychain.lo] Error 1
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tholu/homebrew-tap/issues
```

**Comment by tholu** [comment] 2018-11-12 12:58
That's interesting, however I don't see any obvious issue. What does `brew doctor` say? Are your CLT uptodate?

**Comment by iamjaelee** [comment] 2018-11-13 13:39
I believe my CLT is up-to-date (Xcode 10.1). I check it with the following commands. 

```
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 10.1.0.0.1.1539992718
volume: /
location: /
install-time: 1541985941
groups: com.apple.FindSystemFiles.pkg-group 

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

Digging into a log file, the following command seems to cause the error during `make`:

```
/bin/sh /private/tmp/subversion18-20181113-14978-1d43kwr/subversion-1.8.16/libtool --tag=CC --silent --mode=compile /usr/bin/clang -std=c90  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10   -Werror=unknown-warning-option -Os -w -pipe -march=native -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -O2  -DNDEBUG  -I./subversion/include -I./subversion -I/usr/local/opt/apr/libexec/include/apr-1   -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/subversion18/1.8.16/libexec/serf/include/serf-1 -I/usr/local/opt/sqlite/include -I/usr/include  -o subversion/libsvn_subr/macos_keychain.lo -c subversion/libsvn_subr/macos_keychain.c

...

In file included from subversion/libsvn_subr/macos_keychain.c:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:36:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:354:49: error: expected a version of the form 'major[.minor[.subminor]]'
                                    macos(10.3, API_TO_BE_DEPRECATED),
                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:355:46: error: expected a version of the form 'major[.minor[.subminor]]'
                                    ios(2.0, API_TO_BE_DEPRECATED),
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:356:50: error: expected a version of the form 'major[.minor[.subminor]]'
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
...

4 errors generated.
make: *** [subversion/libsvn_subr/macos_keychain.lo] Error 1
make: *** Waiting for unfinished jobs....
```

I have also tried `brew doctor`, but do not find anything critical. I have tested my brew setup using a couple of packages (wget and tkdiff). Both are built and installed successfully.  

Any clue?  Thanks!

**Comment by genuinefafa** [comment] 2018-11-13 23:54
same issue here! setting up a new installation; my guess is that something new in `xcode` libs (watchos, ios and tvos are not platform subversion actually needs)

**Comment by tholu** [comment] 2018-11-14 06:18
@genuinefafa Are you on 10.13 as well?
@iamjaelee I noticed you are on 10.13 but have the 10.14 SDK installed. Can you try to remove the 10.14 SDK and install 10.13 SDK only?

**Comment by genuinefafa** [comment] 2018-11-14 14:10
hi @tholu and yes, it's 10.14

not sure how can i remove 10.14 and install 10.13; will check later then... but, keep in mind that this was a freshly installed OSX (High Sierra) and it downloaded xcode libs automatically; 

```
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion18/1.8.16/libexec/serf GSSAPI=/usr CC=/usr/bin/clang CFLAGS=-Os -w -pipe -marc
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion18/1.8.16 --with-zlib=/usr --with-sqlite=/usr/local/opt/sqlite --with-serf=/usr/local/Cellar/su
==> make
Last 15 lines from /Users/fafa/Library/Logs/Homebrew/subversion18/04.make:
                                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:355:46: error: expected a version of the form 'major[.minor[.subminor]]'
                                    ios(2.0, API_TO_BE_DEPRECATED),
                                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:356:50: error: expected a version of the form 'major[.minor[.subminor]]'
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
                                              ^
/bin/sh /private/tmp/subversion18-20181114-31096-16irnih/subversion-1.8.16/libtool --tag=CC --silent --mode=compile /usr/bin/clang -std=c90  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10   -Werror=unknown-warning-option -Os -w -pipe -march=native -mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -O2  -DNDEBUG  -I./subversion/include -I./subversion -I/usr/local/opt/apr/libexec/include/apr-1   -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/subversion18/1.8.16/libexec/serf/include/serf-1 -I/usr/local/opt/sqlite/include -I/usr/include  -o subversion/libsvn_subr/pool.lo -c subversion/libsvn_subr/pool.c
/bin/sh /private/tmp/subversion18-20181114-31096-16irnih/subversion-1.8.16/libtool --tag=CC --silent --mode=compile /usr/bin/clang -std=c90  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10   -Werror=unknown-warning-option -Os -w -pipe -march=native -mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -O2  -DNDEBUG  -I./subversion/include -I./subversion -I/usr/local/opt/apr/libexec/include/apr-1   -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/subversion18/1.8.16/libexec/serf/include/serf-1 -I/usr/local/opt/sqlite/include -I/usr/include  -o subversion/libsvn_subr/prompt.lo -c subversion/libsvn_subr/prompt.c
4 errors generated.
make: *** [subversion/libsvn_subr/macos_keychain.lo] Error 1
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tholu/homebrew-tap/issues
```

**Comment by tholu** [comment] 2018-11-14 14:27
@genuinefafa Now I'm confused. Please post the output of `brew config`.

**Comment by tholu** [comment] 2018-11-14 14:31
Can you try the solutions here: https://github.com/Homebrew/homebrew-core/issues/31679#issuecomment-423259873

Seems to be a similar issue (SDK version mismatch of CLT).

**Comment by genuinefafa** [comment] 2018-11-14 14:36
you ask for it! strange that i do not have xCode installed... 

```
$ brew config
HOMEBREW_VERSION: 1.8.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f458aaed494eaab92622f41f9f1967add00b0f4
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c8cb21560f9a7e750601e225e9c954c67221de32
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: vi
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```

**Comment by genuinefafa** [comment] 2018-11-14 14:45
I can confirm that doing `xcode-select --install` DO NOT fixes anything, same issue; it seems like there is a const `API_TO_BE_DEPRECATED` missing in the build `tvos(2.0, API_TO_BE_DEPRECATED));` don't know why would it even need that...

I'm currently downloading 10.13 to check it out... i'll keep you posted

**Comment by tholu** [comment] 2018-11-14 14:49
Ok, so the problem seems to be confirmed - MacOS 10.13 with MacOS SDK 10.14 in CLT. Let me know if downgrading CLT works!

**Comment by genuinefafa** [comment] 2018-11-14 15:01
strange... i did 
`sudo rm -rf /Library/Developer/CommandLineTools`

and then, installed
https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.13_for_Xcode_10.1/Command_Line_Tools_macOS_10.13_for_Xcode_10.1.dmg

And found in `/Library/Developer/CommandLineTools/SDK`
```
$ ls -l /Library/Developer/CommandLineTools/SDKs/
total 0
drwxr-xr-x  7 root  wheel  224 Oct 18 09:52 MacOSX.sdk
lrwxr-xr-x  1 root  wheel   10 Nov 14 11:54 MacOSX10.14.sdk -> MacOSX.sdk
```

i'm puzzled

**Comment by tholu** [comment] 2018-11-14 15:02
Any chance to upgrade to Mojave to solve it?

**Comment by genuinefafa** [comment] 2018-11-14 15:55
LOL, due to brew tooling is that i'm not upgrading... do you believe that upgrading will fix the issue?

**Comment by tholu** [comment] 2018-11-14 16:04
Yes, I think I rebuilt this formula successfully on Mojave in another recent issue. I can verify before you upgrade.

**Comment by genuinefafa** [comment] 2018-11-14 19:57
please do!

**Comment by genuinefafa** [comment] 2018-11-15 03:02
I did an update and it does work! 

```
$ brew config
HOMEBREW_VERSION: 1.8.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f458aaed494eaab92622f41f9f1967add00b0f4
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6739097ca1677ab2742e67e3e674ef301b77fa8c
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: vi
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```

So, Mojave is a must now...

**Comment by tholu** [comment] 2018-11-15 08:14
Sorry, was already sleeping - glad it worked! It seems that CLT are broken for 10.13, and either Apple fixes those or you need to upgrade to Mojave. In the end, the upgrade is probably inevitable.

Closing, @iamjaelee I hope this fixes it for you as well!

**Closed as completed by tholu** 2018-11-15 08:14 UTC

**Comment by iamjaelee** [comment] 2018-11-15 23:58
Upgrading to Mojave works for me, too.  Thanks!
